log_format timing '$remote_addr "$request" $status '
                  'req_time=$request_time '
                  'upstream_resp=$upstream_response_time '
                  'upstream_conn=$upstream_connect_time '
                  'upstream_hdr=$upstream_header_time';

access_log /var/log/nginx/access.log timing;

server {
    listen 80;
    server_name _;
    client_max_body_size 10M;
    # Редирект на HTTPS (раскомментировать после настройки SSL)
    return 301 https://$host$request_uri;

    location / {
        proxy_pass         http://daios-frontend:3000;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}

# HTTPS — раскомментировать после получения сертификата (certbot)
server {
    listen 443 ssl;
    server_name daios.sytes.net;
    client_max_body_size 10M;
    ssl_certificate     /etc/letsencrypt/live/daios.sytes.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/daios.sytes.net/privkey.pem;

    location / {
        proxy_pass http://daios-frontend:3000;
        proxy_set_header Host            $host;
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
